services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    command: -p 5433
    restart: always
    environment:
      - POSTGRES_DB=todennus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    expose:
      - 5433
    networks:
      - POSTGRES
      - PG_ADMIN

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@todennus.com
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - PG_ADMIN
    depends_on:
      - postgresql

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    command: --port 6380
    expose:
      - 6380
    volumes:
      - redis:/data
    networks:
      - REDIS

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    expose:
      - 9000
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - minio:/data
    networks:
      - MINIO

  todennus-docs:
    container_name: todennus-docs
    image: todennus/docs:latest
    command: swagger
    restart: always
    ports:
      - 8888:8080

  todennus-idp:
    container_name: todennus-idp
    image: todennus/idp:latest
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ../idp/.env
    environment:
      - USER_VALIDATION_GRPC=todennus-user-service-rpc:8080
      - TODENNUS_AUTH_CALLBACK_URL=http://todennus-oauth2-service:8080/auth/callback
      - TODENNUS_SESSION_UPDATE_URL=http://localhost:8080/session/update
      - TODENNUS_IDP_SECRET
      - SERVICE_TOKEN_HOST=http://todennus-oauth2-service:8080
      - SERVICE_TOKEN_PATH=/oauth2/token
    networks:
      - TODENNUS

  todennus-migration:
    container_name: todennus-migration
    image: todennus/migration:latest
    command: "--postgres"
    environment:
      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2
      - POSTGRES_LOGLEVEL=1
      - POSTGRES_RETRY_ATTEMPTS=3
      - POSTGRES_RETRY_INTERVAL=5
    networks:
      - POSTGRES
    depends_on:
      - postgresql

  todennus-oauth2-service:
    container_name: todennus-oauth2-service
    image: todennus/oauth2-service:latest
    command: rest
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file:
      - ../oauth2-service/.env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_NODEID=0

      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2

      - REDIS_DB=0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_ADDR=redis:6380

      - SERVICE_USER_GRPC_ADDR=todennus-user-service-rpc:8080
      - SERVICE_OAUTH2_CLIENT_GRPC_ADDR=todennus-oauth2-client-service-rpc:8080
    networks:
      - POSTGRES
      - REDIS
      - TODENNUS
    depends_on:
      - postgresql
      - todennus-migration

  todennus-user-service:
    container_name: todennus-user-service
    image: todennus/user-service:latest
    command: rest
    restart: always
    expose:
      - 8080
    ports:
      - 8081:8080
    env_file:
      - ../user-service/.env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_NODEID=1

      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2

      - REDIS_DB=0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_ADDR=redis:6380

      - SERVICE_OAUTH2_TOKEN_URL=http://todennus-oauth2-service:8080/oauth2/token
      - SERVICE_FILE_GRPC_ADDR=todennus-file-service-rpc:8080
    networks:
      - POSTGRES
      - REDIS
      - TODENNUS
    depends_on:
      - postgresql
      - todennus-migration

  todennus-user-service-rpc:
    container_name: todennus-user-service-rpc
    image: todennus/user-service:latest
    command: grpc
    restart: always
    expose:
      - 8080
    ports:
      - 8082:8080
    env_file:
      - ../user-service/.env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_NODEID=2

      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2

      - REDIS_DB=0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_ADDR=redis:6380

      - SERVICE_OAUTH2_TOKEN_URL=http://todennus-oauth2-service:8080/oauth2/token
      - SERVICE_FILE_GRPC_ADDR=todennus-file-service-rpc:8080
    networks:
      - POSTGRES
      - REDIS
      - TODENNUS
    depends_on:
      - postgresql
      - todennus-migration

  todennus-oauth2-client-service:
    container_name: todennus-oauth2-client-service
    image: todennus/oauth2-client-service:latest
    command: rest
    restart: always
    ports:
      - 8083:8080
    env_file:
      - ../oauth2-client-service/.env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_NODEID=3

      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2
      - POSTGRES_LOGLEVEL=1
      - POSTGRES_RETRY_ATTEMPTS=3
      - POSTGRES_RETRY_INTERVAL=5

      - REDIS_DB=0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_ADDR=redis:6380

      - SERVICE_OAUTH2_TOKEN_URL=http://todennus-oauth2-service:8080/oauth2/token
      - SERVICE_USER_GRPC_ADDR=todennus-user-service-rpc:8080
    networks:
      - POSTGRES
      - REDIS
      - TODENNUS
    depends_on:
      - postgresql
      - todennus-migration

  todennus-oauth2-client-service-rpc:
    container_name: todennus-oauth2-client-service-rpc
    image: todennus/oauth2-client-service:latest
    command: grpc
    restart: always
    expose:
      - 8080
    ports:
      - 8084:8080
    env_file:
      - ../oauth2-client-service/.env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_NODEID=4

      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2
      - POSTGRES_LOGLEVEL=1
      - POSTGRES_RETRY_ATTEMPTS=3
      - POSTGRES_RETRY_INTERVAL=5

      - REDIS_DB=0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_ADDR=redis:6380

      - SERVICE_OAUTH2_TOKEN_URL=http://todennus-oauth2-service:8080/oauth2/token
      - SERVICE_USER_GRPC_ADDR=todennus-user-service-rpc:8080
    networks:
      - POSTGRES
      - REDIS
      - TODENNUS
    depends_on:
      - postgresql
      - todennus-migration

  todennus-file-service:
    container_name: todennus-file-service
    image: todennus/file-service:latest
    command: rest
    restart: always
    ports:
      - 8085:8080
    env_file:
      - ../file-service/.env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_NODEID=5

      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2
      - POSTGRES_LOGLEVEL=1
      - POSTGRES_RETRY_ATTEMPTS=3
      - POSTGRES_RETRY_INTERVAL=5

      - REDIS_DB=0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_ADDR=redis:6380

      - SERVICE_OAUTH2_TOKEN_URL=http://todennus-oauth2-service:8080/oauth2/token
      - SERVICE_USER_GRPC_ADDR=todennus-user-service-rpc:8080

      - MINIO_ENDPOINT=minio:9000
    networks:
      - POSTGRES
      - REDIS
      - TODENNUS
      - MINIO
    depends_on:
      - postgresql
      - todennus-migration

  todennus-file-service-rpc:
    container_name: todennus-file-service-rpc
    image: todennus/file-service:latest
    command: grpc
    restart: always
    ports:
      - 8086:8080
    env_file:
      - ../file-service/.env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_NODEID=6

      - POSTGRES_DSN=postgresql://postgres:postgres@postgresql:5433/todennus?sslmode=disable&connect_timeout=2
      - POSTGRES_LOGLEVEL=1
      - POSTGRES_RETRY_ATTEMPTS=3
      - POSTGRES_RETRY_INTERVAL=5

      - REDIS_DB=0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_ADDR=redis:6380

      - SERVICE_OAUTH2_TOKEN_URL=http://todennus-oauth2-service:8080/oauth2/token
      - SERVICE_USER_GRPC_ADDR=todennus-user-service-rpc:8080

      - MINIO_ENDPOINT=minio:9000
    networks:
      - POSTGRES
      - REDIS
      - TODENNUS
      - MINIO
    depends_on:
      - postgresql
      - todennus-migration

volumes:
  postgresql:
    name: todennus_postgresql
  pgadmin:
    name: todennus_pgadmin
  redis:
    name: todennus_redis
  minio:
    name: todennus_minio

networks:
  PG_ADMIN:
    name: PG_ADMIN
  POSTGRES:
    name: POSTGRES
  REDIS:
    name: REDIS
  TODENNUS:
    name: TODENNUS
  MINIO:
    name: MINIO
